### ISSUE TITLE
NifiCluster reconciliation loop is non-idempotent in ready state

### ISSUE THREAD

**Issue by cannonpalms** [konpyutaika/nifikop#119]
### Basic description
Once a `NifiCluster` has been fully reconciled--all pods created and ready, users/groups have certificates, data flows have been added, etc.--the `NifiCluster` resource continues to be modified by every single iteration of the reconciliation loop. This results in another iteration of the loop being queued, ad nauseum.

This is typically the result of a non-idempotency bug ([example](https://github.com/kubernetes-sigs/controller-runtime/issues/1613)). Some part of the work being done by the [`Reconcile`](https://github.com/konpyutaika/nifikop/blob/master/controllers/nificluster_controller.go#L81) function is causing the resource to be constantly updated.

### Evidence
This can easily be observed in two ways. First, run the following command on a `NifiCluster` once all child resources have been fully reconciled:
```bash
kubectl get nificluster <cluster-name> -o yaml --watch
```

You will see the `status.state` field flickering between `ClusterReconciling` and `ClusterRunning` like so:

![nificluster-status-flickering](https://user-images.githubusercontent.com/2457559/179041040-becc8d0f-131a-4f62-9c79-723598e195be.gif)

Alternatively, you can observe the `resourceVersion` of the object constantly--and rapidly--being incremented. Here's one command that demonstrates this using [`yq`](https://github.com/mikefarah/yq) to extract the field from the yaml output we are `--watch`ing:
```bash
kubectl get nificluster <cluster-name> -o yaml --watch | yq '.metadata.resourceVersion'
```
![nificluster-resourceversion-incrementing](https://user-images.githubusercontent.com/2457559/179042428-1338fdac-da43-4ad6-9d61-747a10fc6f6b.gif)

### Impact
This bug causes pain in several areas. First, is in how GitOps projects like ArgoCD interact with the `NifiCluster` custom resource and some of its children. Because the `NifiCluster` resource is constantly changing, ArgoCD believes that the resource is constantly progressing. Take a look:

![nificluster-argocd](https://user-images.githubusercontent.com/2457559/179043550-9213600b-eb5e-4439-a8b3-165138596a73.gif)

Another common result of this issue is error messages from the k8s api when attempting to modify the `NifiCluster` resource. The error explains that a change to the resource could not be fulfilled due to the fact that the resource was modified in the middle of crafting the request, and is thus no longer the latest version of the resource. These messages can be seen in `nifikop` logs: 

![Screenshot_64](https://user-images.githubusercontent.com/2457559/179044856-a812d109-964b-4d9a-a967-cd7954d3b132.png)

### Additional context
This bug occurs in the latest version of nifikop and for all versions of NiFi. 

There was a slack discussion regarding this bug [https://konpytika.slack.com/archives/C035X6KP684/p1649863690965119](https://konpytika.slack.com/archives/C035X6KP684/p1649863690965119).

**Comment by michael81877** [comment]
I'd really like to see this addressed as well! We see the exact same behavior in our Argo deployments. We also see this in `NifiDataflow` resources.

Additionally, I think the "object has been modified; please apply your changes to the latest version and try again" errors can be resolved by performing patches to specific portions of the CRD instead of updates to the entire object.
