### ISSUE TITLE
NifiCluster CRD has no valid internal listener option for the load balancing port

### ISSUE THREAD

**Issue by cannonpalms** [konpyutaika/nifikop#134]
NiFi uses port `6342` (by default) for its custom load balancing protocol. This is configurable through `nifi.properties` via `nifi.cluster.node.load.balance.port`.

This is **not** the same thing has the "node protocol" port, `nifi.cluster.node.protocol.port` which has a default of `11443`.

The `NifiCluster` CRD [explicitly defines](https://github.com/konpyutaika/nifikop/blob/master/config/crd/bases/nifi.konpyutaika.com_nificlusters.yaml#L1457-L1461) the value "listener" types. For clarity, here is a list of these types and what they do:

| type | nifi property | default value | description |
| --- | --- | --- | --- |
| cluster | `nifi.cluster.node.protocol.port` |  11443 | Used for heartbeats |
| http | `nifi.web.http.port` | 8080 | serves UI, API when TLS not configured |
| https | `nifi.web.https.port` | 8443 | serves UI, API when TLS _is_ configured |
| s2s | `nifi.remote.input.socket.port` | 10443 | Site-to-site protocol used for inter-cluster communication |
| prometheus | N/A | 9090 | Port where the prometheus reporting task can be scraped |

There is actually one additional important port: the port used for NiFi's internal load balancing protocol. This is how nodes share flow files with one another to keep their queues balanced.

When operating in headless mode, only the ports from these internal listeners will be added to the headless service; similarly, in non-headless mode, only the ports from these internal listeners will be added to the "all-node" service. Critically, this means that mesh infrastructure like linkerd and istio is unable to proxy traffic on this port. 

## Suggested action
A new type of internal listener should be added to the CRD: `load-balance`. Docs and examples should reflect this new listener:
```yaml
- type: load-balance
  name: load-balance
  port: 6342
```

Likewise, a bit of Go must be written to ensure that this listener's port is propagated to any "all-node" or "headless" service that nifikop creates.

**Comment by michael81877** [comment]
Raised #138 to address
