### ISSUE TITLE
Improve the pod health checks to monitor cluster status

### ISSUE THREAD

**Issue by r65535** [konpyutaika/nifikop#167]
### What steps will reproduce the bug?

If a node disconnects from a nifi cluster, it'll stay disconnected until I manually delete the pod. I get this error regularly:

Action cannot be performed because there is currently no Cluster Coordinator elected. The request should be tried again after a moment, after a Cluster Coordinator has been automatically elected.

### What is the expected behavior?

The pod should be restarted to rejoin the cluster

### What do you see instead?

Disconnected nodes that don't recover

### Possible solution

Change the pod readiness check to hit `/nifi-api/flow/cluster/summary`?

### NiFiKop version

v0.14.0-release

### Golang version

1.19

### Kubernetes version

v1.23.6-rke2r2

### NiFi version

1.16.0

**Comment by michael81877** [comment]
How does the `/nifi-api/flow/cluster/summary` endpoint respond for standalone clusters?

**Comment by r65535** [comment]
> How does the `/nifi-api/flow/cluster/summary` endpoint respond for standalone nodes?

I hadn't thought of that! The above endpoint isn't available to standalone clusters - so maybe an if statement [here](https://github.com/konpyutaika/nifikop/blob/master/pkg/resources/nifi/pod.go#L378-L388) that uses the above URI if it's clustered, or leaves it as-is if not?

**Comment by michael81877** [comment]
That sounds reasonable!

**Comment by michael81877** [comment]
I've opened #219 as i believe that's a more general solution that can be tailored to specific use cases.
