### ISSUE TITLE
Not able to install nificluster when nifi kop is in different namespace

### ISSUE THREAD

**Issue by narayanbhawar10** [konpyutaika/nifikop#234]
### Is your feature request related to a problem?

When I install NiFi cluster in different namespace then not able to install it because nifikop belongs to different namespace. Is there any already configuration available for separating nifi kop and nifi cluster via namespace.

**Comment by mh013370** [comment]
The `namespaces` setting in the helm chart controls which namespaces the operator watches for CRDs:

https://github.com/konpyutaika/nifikop/tree/master/helm/nifikop

**Comment by narayanbhawar10** [comment]
Thanks @mh013370 Now I am able to progress.
