### ISSUE TITLE
Recommended approach for services to utilise ListenHTTP/HandleHTTPRequest processor

### ISSUE THREAD

**Issue by jayctran** [konpyutaika/nifikop#265]
Hi,

Currently trying to utilise the ListenHTTP processor and when it's started, it spins up a web server to listen to requests on a certain port.

I'm accessing Nifi on our kubernetes cluster with ingress but I couldn't find a way to specify additional external services pointing to this port as they all require an internalListner service. 

Is there a recommended approach to this or a potential enhancement to include custom listenHttp ports as an internal service (ie. a new InternalListener type of 'http-listener')?

**Comment by jayctran** [comment]
Just realised type isn't required and that's how I can set the internal listener.

**Comment by mh013370** [comment]
Yes this is the way! :)
