### ISSUE TITLE
No way to add annotation to PVC

### ISSUE THREAD

**Issue by Carverook** [konpyutaika/nifikop#267]
There is no way to add an annotation to a PVC. Because of this, it is impossible to automatically tag AWS EBS after PVC creation, and there is no point in manually adding tags, since autoscaling works.
Please add this

**Comment by mh013370** [comment]
We can add labels & annotations to attach to PVCs. Looking into this.

**Comment by Carverook** [comment]
Thank you, this is very good news for me.
Can you please tell me when we can expect this fix in the main branch?

**Comment by Carverook** [comment]
Good afternoon) Tell me please, when can I expect a version? We really need it for production)
