### ISSUE TITLE
Ability to change NiFi containerPort protocol (UDP/TCP)

### ISSUE THREAD

**Issue by TimMilton** [konpyutaika/nifikop#319]
### Type of question

General Context

### Support question

Hi. Is there any way to change NiFi containerPort protocol in listenersConfig? (from TCP to UDP). 
When we trying to add `protocol: "UDP"` or `protocolType: "UDP"` field into `spec.listenersConfig.internalListeners` section, we got an error `strict decoding error: unknown field "spec.listenersConfig.internalListeners.protocol"`. 
Thank you.

### NiFiKop version

v1.4.0-release

### Kubernetes version

Client Version: v1.28.2
Server Version: v1.28.2-eks

### NiFi version

1.23.2

**Comment by Carverook** [comment]
We need this too, please implement it.

**Comment by mh013370** [comment]
Raised PR to add.
