### ISSUE TITLE
Changes are not applied after adding tags to PVC

### ISSUE THREAD

**Issue by TimMilton** [konpyutaika/nifikop#332]
### What steps will reproduce the bug?

Hi! It looks like, that we found some issue after adding tags to storageConfigs.metadata.annotations field in nifi yaml configuration. Changes are not applied until the PVC is manually recreated. We are using EBS CSI GP3. Can you please look for solution to this issue?

### What is the expected behavior?

Applying tags changes without manual intervention in the PVC.

### What do you see instead?

No changes applied in tags until the PVC is manually recreated.

### NiFiKop version

v1.5.0-release

### Golang version

-

### Kubernetes version

Client Version: v1.28.2
Server Version: v1.28.2-eks

### NiFi version

1.23.2

**Comment by mh013370** [comment]
Can you please share the `NifiCluster` configuration you're using?

**Comment by mh013370** [comment]
I think i've verified this as a bug, so working on a fix.

**Comment by Carverook** [comment]
Do you still need any information from us?
