### ISSUE TITLE
Connection refused on every port Helm Chart deployment

### ISSUE THREAD

**Issue by Aptul9** [konpyutaika/nifikop#468]
### What steps will reproduce the bug?

helm install nifikop \
    oci://ghcr.io/konpyutaika/helm-charts/nifikop \
    --namespace=nifi \
    --version 1.10.0 \
    --set image.tag=v1.10.0-release \
    --set resources.requests.memory=256Mi \
    --set resources.requests.cpu=250m \
    --set resources.limits.memory=256Mi \
    --set resources.limits.cpu=250m \
    --set namespaces={"nifi"} --create-namespace

helm install zookeeper oci://registry-1.docker.io/bitnamicharts/zookeeper \
    --namespace=zookeeper \
    --set resources.requests.memory=256Mi \
    --set resources.requests.cpu=250m \
    --set resources.limits.memory=256Mi \
    --set resources.limits.cpu=250m \
    --set global.storageClass=standard \
    --set networkPolicy.enabled=true \
    --set replicaCount=3 \
    --create-namespace
    
  Then I applied the simple nifi cluster file on the same namespace: https://github.com/konpyutaika/nifikop/blob/master/config/samples/simplenificluster.yaml

### What is the expected behavior?

I should be able to access nifi through it's load balancer or by port-forwarding.

### What do you see instead?

I can't access nifi, even if I ssh into the pod and I do curl localhost on every port specified in the file, I do get a connection refused error.

### NiFiKop version

1.10

### Golang version

N/A

### Kubernetes version

Minikube latest

### NiFi version

1.23

**Comment by Aptul9** [comment]
After updating the chart to version 1.11 
helm upgrade -i nifikop \
    oci://ghcr.io/konpyutaika/helm-charts/nifikop \
    --namespace=nifi \
    --version 1.11.0 \
    --set image.tag=v1.11.0-release \
    --set resources.requests.memory=256Mi \
    --set resources.requests.cpu=250m \
    --set resources.limits.memory=256Mi \
    --set resources.limits.cpu=250m \
    --set namespaces={"nifi"} --create-namespace

and installing the nifi-cluster chart:
helm upgrade -i nificluster oci://ghcr.io/konpyutaika/helm-charts/nifi-cluster --version 1.11.0 -f values.yaml -n nifi
with the following values:
cluster:
  manager: kubernetes

And enabling kube state management: https://konpyutaika.github.io/nifikop/docs/3_manage_nifi/1_manage_clusters/1_deploy_cluster/1_quick_start#enabling-kubernetes-state-management

I still can't fully start the cluster, the operator keeps deleting and recreating the pod, but the cluster doesn't start.

**Comment by juldrixx** [comment]
> After updating the chart to version 1.11 helm upgrade -i nifikop oci://ghcr.io/konpyutaika/helm-charts/nifikop --namespace=nifi --version 1.11.0 --set image.tag=v1.11.0-release --set resources.requests.memory=256Mi --set resources.requests.cpu=250m --set resources.limits.memory=256Mi --set resources.limits.cpu=250m --set namespaces={"nifi"} --create-namespace
> 
> and installing the nifi-cluster chart: helm upgrade -i nificluster oci://ghcr.io/konpyutaika/helm-charts/nifi-cluster --version 1.11.0 -f values.yaml -n nifi with the following values: cluster: manager: kubernetes
> 
> And enabling kube state management: https://konpyutaika.github.io/nifikop/docs/3_manage_nifi/1_manage_clusters/1_deploy_cluster/1_quick_start#enabling-kubernetes-state-management
> 
> I still can't fully start the cluster, the operator keeps deleting and recreating the pod, but the cluster doesn't start.

Can you share the operator logs?

**Comment by Aptul9** [comment]
Note: I've tried these steps both in minikube and on RKE2 and Kubernetes v1.30, and I got the same response.

```
{"level":"error","time":"2024-10-28T13:50:10.686Z","logger":"nifi_client","caller":"nificlient/common.go:33","msg":"Error during talking to nifi node","error":"Get \"http://nificluster-nifi-cluster-headless.nifi.svc.cluster.local:8080/nifi-api/controller/cluster\": dial tcp: lookup nificluster-nifi-cluster-headless.nifi.svc.cluster.local on 10.96.0.10:53: no such host","stacktrace":"[github.com/konpyutaika/nifikop/pkg/nificlient.errorGetOperation](http://github.com/konpyutaika/nifikop/pkg/nificlient.errorGetOperation)\n\t/workspace/pkg/nificlient/common.go:33\[ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).DescribeCluster](http://ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).DescribeCluster)\n\t/workspace/pkg/nificlient/system.go:17\[ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).Build](http://ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).Build)\n\t/workspace/pkg/nificlient/client.go:182\[ngithub.com/konpyutaika/nifikop/pkg/nificlient.NewFromConfig](http://ngithub.com/konpyutaika/nifikop/pkg/nificlient.NewFromConfig)\n\t/workspace/pkg/nificlient/client.go:203\[ngithub.com/konpyutaika/nifikop/pkg/common.NewClusterConnection](http://ngithub.com/konpyutaika/nifikop/pkg/common.NewClusterConnection)\n\t/workspace/pkg/common/common.go:56\[ngithub.com/konpyutaika/nifikop/pkg/clientwrappers/scale.EnsureRemovedNodes](http://ngithub.com/konpyutaika/nifikop/pkg/clientwrappers/scale.EnsureRemovedNodes)\n\t/workspace/pkg/clientwrappers/scale/scale.go:185\[ngithub.com/konpyutaika/nifikop/pkg/resources/nifi.(*Reconciler).Reconcile](http://ngithub.com/konpyutaika/nifikop/pkg/resources/nifi.(*Reconciler).Reconcile)\n\t/workspace/pkg/resources/nifi/nifi.go:252\[ngithub.com/konpyutaika/nifikop/internal/controller.(*NifiClusterReconciler).Reconcile](http://ngithub.com/konpyutaika/nifikop/internal/controller.(*NifiClusterReconciler).Reconcile)\n\t/workspace/internal/controller/nificluster_controller.go:148\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"}
{"level":"info","time":"2024-10-28T13:50:10.686Z","logger":"controller.NifiCluster","caller":"controller/nificluster_controller.go:152","msg":"Nodes unreachable, may still be starting up","reason":"could not connect to nifi nodes: nificluster-nifi-cluster-headless.nifi.svc.cluster.local:8080: Get \"http://nificluster-nifi-cluster-headless.nifi.svc.cluster.local:8080/nifi-api/controller/cluster\": dial tcp: lookup nificluster-nifi-cluster-headless.nifi.svc.cluster.local on 10.96.0.10:53: no such host"}
```

**Comment by juldrixx** [comment]
> Note: I've tried these steps both in minikube and on RKE2 and Kubernetes v1.30, and I got the same response.
> 
> ```
> {"level":"error","time":"2024-10-28T13:50:10.686Z","logger":"nifi_client","caller":"nificlient/common.go:33","msg":"Error during talking to nifi node","error":"Get \"http://nificluster-nifi-cluster-headless.nifi.svc.cluster.local:8080/nifi-api/controller/cluster\": dial tcp: lookup nificluster-nifi-cluster-headless.nifi.svc.cluster.local on 10.96.0.10:53: no such host","stacktrace":"[github.com/konpyutaika/nifikop/pkg/nificlient.errorGetOperation](http://github.com/konpyutaika/nifikop/pkg/nificlient.errorGetOperation)\n\t/workspace/pkg/nificlient/common.go:33\[ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).DescribeCluster](http://ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).DescribeCluster)\n\t/workspace/pkg/nificlient/system.go:17\[ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).Build](http://ngithub.com/konpyutaika/nifikop/pkg/nificlient.(*nifiClient).Build)\n\t/workspace/pkg/nificlient/client.go:182\[ngithub.com/konpyutaika/nifikop/pkg/nificlient.NewFromConfig](http://ngithub.com/konpyutaika/nifikop/pkg/nificlient.NewFromConfig)\n\t/workspace/pkg/nificlient/client.go:203\[ngithub.com/konpyutaika/nifikop/pkg/common.NewClusterConnection](http://ngithub.com/konpyutaika/nifikop/pkg/common.NewClusterConnection)\n\t/workspace/pkg/common/common.go:56\[ngithub.com/konpyutaika/nifikop/pkg/clientwrappers/scale.EnsureRemovedNodes](http://ngithub.com/konpyutaika/nifikop/pkg/clientwrappers/scale.EnsureRemovedNodes)\n\t/workspace/pkg/clientwrappers/scale/scale.go:185\[ngithub.com/konpyutaika/nifikop/pkg/resources/nifi.(*Reconciler).Reconcile](http://ngithub.com/konpyutaika/nifikop/pkg/resources/nifi.(*Reconciler).Reconcile)\n\t/workspace/pkg/resources/nifi/nifi.go:252\[ngithub.com/konpyutaika/nifikop/internal/controller.(*NifiClusterReconciler).Reconcile](http://ngithub.com/konpyutaika/nifikop/internal/controller.(*NifiClusterReconciler).Reconcile)\n\t/workspace/internal/controller/nificluster_controller.go:148\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"}
> {"level":"info","time":"2024-10-28T13:50:10.686Z","logger":"controller.NifiCluster","caller":"controller/nificluster_controller.go:152","msg":"Nodes unreachable, may still be starting up","reason":"could not connect to nifi nodes: nificluster-nifi-cluster-headless.nifi.svc.cluster.local:8080: Get \"http://nificluster-nifi-cluster-headless.nifi.svc.cluster.local:8080/nifi-api/controller/cluster\": dial tcp: lookup nificluster-nifi-cluster-headless.nifi.svc.cluster.local on 10.96.0.10:53: no such host"}
> ```

And can you share logs from NiFi app-log file?

**Comment by Aptul9** [comment]
where is it?

**Comment by juldrixx** [comment]
in `./logs/nifi-app.log` in the nifi pod.

**Comment by Aptul9** [comment]
Are you talking about nifikop or nifi-cluster? because as said, the pods get terminated and recreated continuously, however you can easily reproduce it by:
installing the nifikop
installing the service account
installing the nifi-cluster

**Comment by juldrixx** [comment]
So, the reasons it's failing:
- First, you need to override the nifi version because it will by default use 1.26 but the kubernetes cluster management only works starting 2.0.0-M2.
- But it's not the reason NiFi was crashing, it's because the property (in nifi.properties) nifi.sensitive.props.key needs to be set and the chart does not do it for you.
- and lastly there is an issue with the current chart that does not set the serviceAccount to right place :perplexe: (our fault, I will fix it for a future release).


So you need to put this in your `values.yaml`:
```yaml

cluster:
  manager: kubernetes
  image:
    tag: 2.0.0-M4
  nifiProperties:
    overrideConfigs: |-
      nifi.sensitive.props.key=thisisabadsensitivepropskey
  nodeConfigGroups:
    default-group:
      serviceAccountName: nificluster-nifi-cluster
 ```
