### ISSUE TITLE
nifikop incompatible with cert-manager 1.6.0+

### ISSUE THREAD

**Issue by juldrixx** [konpyutaika/nifikop#57]
From nifikop created by [michael81877](https://github.com/michael81877): Orange-OpenSource/nifikop#153  

## Bug Report

As of `cert-manager` v1.6.0, it no longer publishes API versions `v1alpha2, v1alpha3, and v1beta1`. nifikop should be updated to support API `v1`, which was introduced in cert-manager `v0.16`: 

https://github.com/jetstack/cert-manager/releases/tag/v1.6.0

This means you cannot run cert-manager v1.6.0 or later with nifikop.

**Environment**
* nifikop version: 0.7.2

* go version:

* Kubernetes version information: 1.21

* Kubernetes cluster kind: 

* NiFi version: 1.14.0

**Possible Solution**
Update nifikop to support cert-manager v1 CRDs

**Comment by juldrixx** [comment]
> Hello @erdrix , We are evaluating nifikop and we are having this issue. We are willing to contribute to solve this.
> 
> I see there is an open PR, how can we help to get this merged soon

The PR is up :)

https://github.com/Orange-OpenSource/nifikop/pull/154

**Comment by juldrixx** [comment]
Hello @erdrix , We are evaluating nifikop and we are having this issue. We are willing to contribute to solve this.

I see there is an open PR, how can we help to get this merged soon

**Comment by michael81877** [comment]
This can be closed
