### ISSUE TITLE
Add ability to configure maximum event driven thread count

### ISSUE THREAD

**Issue by juldrixx** [konpyutaika/nifikop#66]
From nifikop created by [michael81877](https://github.com/michael81877): Orange-OpenSource/nifikop#183  

## Feature Request

**Is your feature request related to a problem? Please describe.**

Like you can configure `maximumTimerDrivenThreadCount`, add ability to configure the `maximumEventDrivenThreadCount`. Right now it must be configured via the nifi UI.

**Comment by michael81877** [comment]
This can be closed. Has been implemented.
