### ISSUE TITLE
How to access Slack channel withou orange.com email?

### ISSUE THREAD

**Issue by juldrixx** [konpyutaika/nifikop#67]
From nifikop created by [sanamart](https://github.com/sanamart): Orange-OpenSource/nifikop#185  

I would like to access the slack channel but i can not do it without an orange account. Can anyone grant me access with a different email address?

Thanks.

**Comment by michael81877** [comment]
I think this can be closed now that this [Slack]([Slack](https://join.slack.com/t/konpytika/shared_invite/zt-14md072lv-Jr8mqYoeUrqzfZF~YGUpXA)) invite link exists in the project README.
