### ISSUE TITLE
Unknown field "serviceAnnotations" with last CRD

### ISSUE THREAD

**Issue by zepouet** [konpyutaika/nifikop#92]
## Bug Report

The deployment of the example command line breaks.

``
kubectl create -n nifi -f config/samples/simplenificluster.yaml
``

* Kubernetes cluster kind:  GKE

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:50:27Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

`
➜  nifikop git:(master) kubectl create -n nifi -f config/samples/simplenificluster.yaml
I0505 21:55:30.757329   63607 versioner.go:58] no Auth Provider found for name "gcp"
error: error validating "config/samples/simplenificluster.yaml": error validating data: [ValidationError(NifiCluster.spec.externalServices[1]): unknown field "serviceAnnotations" in com.konpyutaika.nifi.v1alpha1.NifiCluster.spec.externalServices, ValidationError(NifiCluster.spec.externalServices[2]): unknown field "serviceAnnotations" in com.konpyutaika.nifi.v1alpha1.NifiCluster.spec.externalServices]; if you choose to ignore these errors, turn validation off with --validate=false
`

To solve I need to remove the serviceAnnotations but it is strange. I think the problem is elsewhere because it runs the creation but no way to use Nifi after.

Thanks a lot,
Best regards

**Comment by juldrixx** [comment]
The example is incorrect, the `serviceAnnotations` field is not present any more. It has been replaced by a [`metadata`](https://konpyutaika.github.io/nifikop/docs/5_references/1_nifi_cluster/7_external_service_config#externalserviceconfig) field.

I will update the sample.
